### Develop load_ev_data() function

In [16]:
import pandas as pd

In [17]:
ev_url = "https://api.iea.org/evs?parameters=EV%20sales&category=Historical&mode=Cars&csv=true"

In [18]:
ev_df = pd.read_csv(ev_url)
ev_df.head()

,region,category,parameter,mode,powertrain,year,unit,value
0,Africa,Historical,EV stock,Cars,BEV,2013,Vehicles,34.00000
1,Africa,Historical,EV sales,Cars,BEV,2013,Vehicles,34.00000
2,Africa,Historical,EV stock share,Cars,EV,2013,percent,0.00014
3,Africa,Historical,EV sales share,Cars,EV,2013,percent,0.00190
4,Africa,Historical,EV sales share,Cars,EV,2014,percent,0.00078

In [19]:
# Loop through each column, show the classes of categorical columns and describe of numerical columns
for col in ev_df.columns:
    print(f"Column: {col}")
    if ev_df[col].dtype == "object":
        print(f"{col}: {ev_df[col].unique()}")
    else:
        print(f"{col}: {ev_df[col].describe()}")
    print("\n")

Column: region
region: ['Africa' 'Asia Pacific' 'Australia' 'Austria' 'Belgium' 'Brazil'
 'Bulgaria' 'Canada' 'Central and South America' 'Chile' 'China'
 'Colombia' 'Costa Rica' 'Croatia' 'Cyprus' 'Czech Republic' 'Denmark'
 'Estonia' 'EU27' 'Europe' 'Finland' 'France' 'Germany' 'Greece' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Ireland' 'Israel' 'Italy' 'Japan' 'Korea'
 'Latvia' 'Lithuania' 'Luxembourg' 'Malaysia' 'Mexico'
 'Middle East and Caspian' 'Netherlands' 'New Zealand' 'North America'
 'Norway' 'Poland' 'Portugal' 'Rest of the world' 'Romania' 'Russia'
 'Seychelles' 'Slovakia' 'Slovenia' 'South Africa' 'Spain' 'Sweden'
 'Switzerland' 'Thailand' 'Turkiye' 'United Kingdom' 'USA' 'Uzbekistan'
 'Viet Nam' 'World']


Column: category
category: ['Historical']


Column: parameter
parameter: ['EV stock' 'EV sales' 'EV stock share' 'EV sales share'
 'Oil displacement Mbd' 'Oil displacement, million lge' 'Battery demand']


Column: mode
mode: ['Cars']


Column: powertrain
powertrain: ['BEV' 'EV' 'PHEV' 'FCEV']


Column: year
year: count    4970.000000
mean     2017.955936
std         4.054900
min      2010.000000
25%      2015.000000
50%      2018.000000
75%      2021.000000
max      2024.000000
Name: year, dtype: float64


Column: unit
unit: ['Vehicles' 'percent' 'Million barrels per day'
 'Oil displacement, million lge' 'GWh']


Column: value
value: count    4.970000e+03
mean     1.465444e+05
std      1.177559e+06
min      1.600000e-05
25%      2.000000e+00
50%      1.550000e+02
75%      7.900000e+03
max      3.900000e+07
Name: value, dtype: float64

In [20]:
# Split the data into ev_sales and ev_sales_share
ev_sales = ev_df[ev_df["parameter"] == "EV sales"]

ev_sales_share = ev_df[ev_df["parameter"] == "EV sales share"]

In [21]:
# For ev_sales, drop the columns: category, parameter, mode, unit
ev_sales = ev_sales.drop(columns=["category", "parameter", "mode", "unit"])

# For ev_sales_share, drop the columns: category, parameter, mode, unit
ev_sales_share = ev_sales_share.drop(columns=["category", "parameter", "powertrain", "mode", "unit"])

In [23]:
ev_sales

      region powertrain  year       value
1     Africa        BEV  2013        34.0
6     Africa        BEV  2014        14.0
9     Africa       PHEV  2014         1.0
10    Africa       PHEV  2015       120.0
13    Africa        BEV  2015       120.0
...      ...        ...   ...         ...
4951   World        BEV  2023   9500000.0
4953   World       PHEV  2023   4200000.0
4964   World       PHEV  2024   6500000.0
4966   World        BEV  2024  11000000.0
4969   World       FCEV  2024      5300.0

[1727 rows x 4 columns]

In [24]:
def load_ev_data():
    ev_url = "https://api.iea.org/evs?parameters=EV%20sales&category=Historical&mode=Cars&csv=true"
    ev_df = pd.read_csv(ev_url)
    # Split the data into ev_sales and ev_sales_share
    ev_sales = ev_df[ev_df["parameter"] == "EV sales"]
    ev_sales_share = ev_df[ev_df["parameter"] == "EV sales share"]
    # For ev_sales, drop the columns: category, parameter, mode, unit
    ev_sales = ev_sales.drop(columns=["category", "parameter", "mode", "unit"])
    # For ev_sales_share, drop the columns: category, parameter, mode, unit
    ev_sales_share = ev_sales_share.drop(columns=["category", "parameter", "powertrain", "mode", "unit"])
    return ev_sales, ev_sales_share

In [27]:
ev_sales, ev_sales_share = load_ev_data()

display(ev_sales)
display(ev_sales_share)

      region powertrain  year       value
1     Africa        BEV  2013        34.0
6     Africa        BEV  2014        14.0
9     Africa       PHEV  2014         1.0
10    Africa       PHEV  2015       120.0
13    Africa        BEV  2015       120.0
...      ...        ...   ...         ...
4951   World        BEV  2023   9500000.0
4953   World       PHEV  2023   4200000.0
4964   World       PHEV  2024   6500000.0
4966   World        BEV  2024  11000000.0
4969   World       FCEV  2024      5300.0

[1727 rows x 4 columns]

      region  year     value
3     Africa  2013   0.00190
4     Africa  2014   0.00078
15    Africa  2015   0.01300
16    Africa  2016   0.02200
27    Africa  2017   0.01200
...      ...   ...       ...
4915   World  2020   4.40000
4936   World  2021   9.30000
4937   World  2022  15.00000
4958   World  2023  18.00000
4959   World  2024  22.00000

[780 rows x 3 columns]